services:
  postgres:
    image: postgres
    container_name: radioswitch-postgres
    restart: always
    volumes:
      - radioswitch-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radioswitch-nest-api
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env
volumes:
  radioswitch-db-data:
